version: '3.8'

services:
  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: jaeger
    ports:
      - "16686:16686"  # UI do Jaeger
      - "4317:4317"    # OTLP gRPC Receiver (para OpenTelemetry)
      - "4318:4318"    # OTLP HTTP Receiver (para OpenTelemetry)
      - "14268:14268"  # Collector
      - "14250:14250"
      - "6831:6831/udp" # Agent UDP
      - "6832:6832/udp" # Agent UDP
    environment:
      - COLLECTOR_ZIPKIN_HTTP_PORT=9411
    restart: always

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"  # UI do Grafana
    restart: always
    depends_on:
      - jaeger
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana_data:/var/lib/grafana

volumes:
  grafana_data:
